server:
  port: 8081

spring:
  application:
    name: server
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

jwt:
  secret-key: 635266556A586E3272357538782F4125442A472D4B6150645367566B59703373
  expiration: 86400000

logging:
  pattern.console: '%white([%thread]) %highlight(%-5level) %cyan(%logger{5}) %magenta([%file:%-4L]) - %msg%n'
  level:
    root: INFO
