### Agent: request game status
POST http://localhost:8082/game/status

### Agent: request game status
POST http://localhost:8082/game/command
Content-Type: application/json

{
  "gameId": 1,
  "objectId": 11,
  "operationId": 111,
  "operationArgs": []
}
