server:
  port: 8081

spring:
  application:
    name: server

logging:
  pattern.console: '%white([%thread]) %highlight(%-5level) %cyan(%logger{5}) %magenta([%file:%-4L]) - %msg%n'
  level:
    root: INFO
